Schedule
target-ready-2023/target-ready-results-service pull request #2
Opened 2023-07-28 10:32 UTC by Chshravani

This branch contains
Class API
Subject API
Schedule API
Student API

2023-07-31 08:17 UTC, Chshravani commented
1. This branch contains, 
    class service
    subject service
    schedule service
    student service
    results service

2. Collections involved in these APIs are class, results, schedule, student.

3. Testing- JUnit is used.
    Testing is done for service and controller layer of class API, schedule API, subject API, results API.

4. class service, subject services are  completely done.
    schedule service, student service, results service are in progress.

2023-07-31 10:21 UTC, IamYashwant requested changes
Few places we have logging and few places its not Ex. check controller 3 doesn't have logging and 2 have. please make logging through. it will help you debug later.

Good to see test cases. nice job there.

2023-07-31 10:21 UTC, IamYashwant commented on src/main/java/com/target/targetreadyresultsservice/controller/ClassController.java
> +            if (classes != null && classes.toString() !="") {
why this check on a list classes.toString() !="" ?
you can check for null and empty

2023-07-31 10:21 UTC, IamYashwant commented on src/main/java/com/target/targetreadyresultsservice/Exception/BlankValueException.java
> +    public BlankValueException(){
you can put default messages to all exceptions.

2023-07-31 10:21 UTC, IamYashwant commented on build.gradle
> +    implementation 'org.hibernate.validator:hibernate-validator:8.0.0.Final'
group it accordingly. ex. all implementation together

2023-07-31 10:21 UTC, IamYashwant commented on src/main/java/com/target/targetreadyresultsservice/controller/ResultsController.java
> +             @RequestParam("scheudleName") String scName
acyear 
follow the same convention like scName

2023-07-31 10:21 UTC, IamYashwant commented on src/main/java/com/target/targetreadyresultsservice/model/Subject.java
> +        this.maxTestMarks=maxTestMarks;
care the formatting.

2023-07-31 10:21 UTC, IamYashwant commented on src/main/java/com/target/targetreadyresultsservice/service/ScheduleService.java
> +    public void exceptionChecks(Schedule schedule){
nice

2023-07-31 10:21 UTC, IamYashwant commented on src/main/java/com/target/targetreadyresultsservice/service/SubjectService.java
> +        {   log.info("Subject already present");
please take care of the code formatting

2023-07-31 10:21 UTC, IamYashwant commented on src/main/java/com/target/targetreadyresultsservice/service/SubjectService.java
> +            List<Subject> subjects=subjectRepository.findBySubjectNameIgnoreCase(subjectName);
same code formatting

2023-08-16 04:33 UTC, MaheshYadavalli approved these changes

2023-08-16 16:15 UTC, merged